#version: "3.8"

services:
  backend:
    build: ./backend
    container_name: accountbook-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - accountbook-net

  frontend:
    build: ./client
    container_name: accountbook-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - accountbook-net
    depends_on:
      - backend

networks:
  accountbook-net:
    driver: bridge